name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: |
            ${{ secrets.HOST }}
      - name: Deploy to server
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PROJECT_PATH: ${{ secrets.PROJECT_PATH }}
        run: |
          ssh -o StrictHostKeyChecking=no $USERNAME@$HOST '
          cd ../var/www/reboot-portal &&
          git pull origin main &&
          npm install &&
          npm run build
          '
